[package]
name = "debug-diff"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = { git = "https://github.com/zesterer/chumsky" }

[dependencies.clap]
features = ["derive"]
version = "4.1.8"
